tests: Add basic arithmetic tests.

diff --git a/tests/run-test b/tests/run-test
--- a/tests/run-test
+++ b/tests/run-test
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 usage() {
-	echo "Usage: $0 <test db> <test dir>"
+	echo "Usage: $0 <test dir>"
 }
 
-(cat $2/test.in ; echo "; shutdown()") | ./moo -n single $1 /dev/null 2>$2/run.err | grep '=>' | head -n -1 > $2/run.out
-if ! diff -u $2/test.out $2/run.out; then
-	echo "$2: failed"
+(cat $1/test.in | grep -v '^#' | sed 's/^/; /'; echo "; shutdown()") | ./moo -n single Test.db /dev/null 2>$1/run.err | grep '=>' | sed 's/^=> //' | head -n -1 > $1/run.out
+if ! diff -u $1/test.out $1/run.out; then
+	echo "$1: failed"
 else
-	echo "$2: ok"
+	echo "$1: ok"
 fi
